#!/usr/bin/env bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------
if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi
#------------------------------------------------------------------------

COLOR_GE80=${COLOR_GE80:-#00FF00}
COLOR_GE60=${COLOR_GE60:-#FFF600}
COLOR_GE40=${COLOR_GE40:-#FFAE00}
COLOR_LOWR=${COLOR_LOWR:-#FF0000}
COLOR_DOWN=${COLOR_DOWN:-#FF0000}

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "wifi down"
    echo "wifi down"
    echo $COLOR_DOWN
    exit
fi

#------------------------------------------------------------------------

QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

iw dev ${INTERFACE} link |\
    awk \
    -v COLOR_GE80="$COLOR_GE80" \
    -v COLOR_GE60="$COLOR_GE60" \
    -v COLOR_GE40="$COLOR_GE40" \
    -v COLOR_LOWR="$COLOR_LOWR" \
    '
    /SSID/ { SSID=$2 } 
    /signal.*dBm/ { SIGNAL=$2 }
    END {
	strength=(SIGNAL > -50 ? 100 :(SIGNAL < -100 ? 0 : (SIGNAL+100)*2));
	printf "%s (%s%%)\n", SSID, strength
	if ( strength >= 80 ) {
	    print COLOR_GE80 
	} else if ( strength >= 60 ) {
	    print COLOR_GE60
	} else if ( strength >= 40 ) {
	    print COLOR_GE40
	} else {
	    print COLOR_LOWR
	}
    }
    ' 
