#!/bin/bash
#
# Copyright © 2020 Filip Paskali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case $BLOCK_BUTTON in
	1|3) amixer set Capture toggle > /dev/null ;;
esac

RED='#FF0000'

MIC_STATUS="$( amixer get Capture | awk '/Front Left:/ {print $7; exit}' )"

case $MIC_STATUS in
    '[on]')
      echo "ON"
      ;;
    '[off]')
      printf "%s\n" \
      	"OFF" \
	"" \
	"$RED"
      ;;
    *)
      echo "Unknown status :$MIC_STATUS:"
      ;;
esac
