#!/bin/bash
#
# Copyright © 2020 Filip Paskali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

readonly DEFAULT_SOURCE="$(pactl info | grep "Default Source" | awk '{print $3}')"

case $BLOCK_BUTTON in
	1|3) pactl set-source-mute $DEFAULT_SOURCE toggle > /dev/null ;;
esac


MUTED="$(pactl list sources | grep -A 15 "Name: $DEFAULT_SOURCE" | grep Mute | awk '{print $2}')"

RED='#FF0000'

case "$MUTED" in
    'yes')
      printf "%s\n" \
      	"OFF" \
	    "" \
	    "$RED"
      ;;
    'no')
      echo "ON"
      ;;
    *)
      echo "Unknown status :$MIC_STATUS:"
      ;;
esac
